= OneCX Data
:idprefix:
:idseparator: -
:imagesdir: ../../images

The OneCX Local Environment contains data required for initial xref:../scripts/start.adoc[startup]. This data is usually automatically xref:../scripts/import.adoc[imported] after the services have started.

This is an overview of the data and how its organized.


.OneCX Default Data
[.stripes-even,cols="20,~"]
|===
| Data Type
| Description

| Assignments
| Relationship between roles and permissions. Managed in xref:documentation:onecx-permission:page$index.adoc[Permission Management].

| Parameters
| Used by some applications and managed in xref:documentation:onecx-parameter:page$index.adoc[Parameter Management].

| Permissions
| Declared and used in applications. Managed in xref:documentation:onecx-permission:page$index.adoc[Permission Management].

| Products (Applications)
| Application data (components, slots etc.). Managed in xref:documentation:onecx-product-store:page$index.adoc[Application Store].

| Tenants
| Represents a customer or organizational unit using OneCX. Managed in xref:documentation:onecx-tenant:page$index.adoc[Tenant Management].

| Themes
| Used to customize the look and feel of OneCX for a tenant. Managed in xref:documentation:onecx-theme:page$index.adoc[Theme Management].

| Workspaces
| Represents a customer or organizational unit using OneCX. Managed in xref:documentation:onecx-workspace:page$index.adoc[Workspace Management].
|===


== How the Data are organized and imported
The directory *onecx-data* in the *onecx-local-env* repository contains all data files and scripts needed to import data into the OneCX Local Environment.

The xref:../scripts/import.adoc[import-onecx.sh] script is used to import data needed by the OneCX services. It can be run from the root directory of the *onecx-local-env* repository.
It starts several scripts that import data for the different services. All data files are in JSON format and usually related to a tenant or an application.

The import scripts are using node.js for reading the data, split them in batches and call the respective service APIs to import the data.
Each script is responsible for importing a specific type of data, e.g., workspaces, themes, permissions, etc.


[#adding-new-files]
== Adding New Files

To add new files to the `imports` directory, follow these guidelines:

1. **Naming Conventions** - use consistent naming patterns based on the type of data being imported. The patterns are listed in the <<convention-and-file-list, Convention and file list>> section.

2. **File Structure** - JSON files should adhere to the existing structure that is compliant with the respective service's API.

3. **Script Updates** - If adding a new type of data, add new import script that includes new files and uses the appropriate service. Make sure to define the structure of the JSON files.

4. **Testing** - Test the import process by running the relevant script and verifying the data in the environment.

By adhering to these conventions, you can ensure consistency and maintainability in the OneCX Local Environment.