echo "##### Importing assignments"

#dtag_token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJFOGU0NjVtNW0wTGFlRTQ3aFNwYjJOZzgtbVdkUVJoN1VWT1RxVUhuTkJzIn0.eyJleHAiOjE3MTc3MDIxNDUsImlhdCI6MTcxNzcwMTg0NSwiYXV0aF90aW1lIjoxNzE3NzAxODQ1LCJqdGkiOiIzNTQ3OGNkOC02MjlkLTRmMmEtYjc3OC0yOTE0MDYxNTk3MDciLCJpc3MiOiJodHRwOi8va2V5Y2xvYWstYXBwL3JlYWxtcy9HaWdhYml0SHViIiwiYXVkIjoib25lY3gtc2hlbGwtdWktY2xpZW50Iiwic3ViIjoiNDliNDBmZTUtOGU5Yy00MDZlLWI5YmQtZmNhMzEzZmRiZTEzIiwidHlwIjoiSUQiLCJhenAiOiJvbmVjeC1zaGVsbC11aS1jbGllbnQiLCJub25jZSI6IjE1MTYxYzZkLWE5MDAtNDVmMi04MWJiLWIwZDAzMTdmNGJmMiIsInNlc3Npb25fc3RhdGUiOiIyODg1ZTk2Ny04MTgxLTRkOWYtYWY0Zi1lNWFmY2Q2YmFhYzAiLCJhdF9oYXNoIjoiM1hkMnp1UmRlY2ZtZ1lYMl93M2w2QSIsImFjciI6IjEiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicHJlZmVycmVkX3VzZXJuYW1lIjoib25lY3gtZHRhZyIsInBhcnR5SWQiOlsiMTAwMDkiXSwib3JnSWQiOiJkdGFnIn0.g9X8ZZmfsWAraGUkRBr8gRZ67LZNUzKOjGrPNUcx5ESkeyIB0UWRW9LYNxsdFkXagg0wO4RaTE9KcIXoEux81U3OghZTPekCVbAe82LqdfCRIfMBZy-XKL3MZNa9NY-DyZRE4-7wMzMDNXbmLEiOGbS5bdlNpDzfEyZdm449hRZD8FSBoO2zt9YJFuLUVvA4Lpu7kjBursHhH2HNltvt6JEOBpjajnTiSNdqFRNqlNKrdogAW2r3yEvP_gK28BgUr-nggkD35fWRDwj4McdFvR1RNGLIzeYNfLAIIceQeAdEN_LLut023kpuC1SOBkJHTiaBefHbD1NbUyOCQNho0w
#gfnw_token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJFOGU0NjVtNW0wTGFlRTQ3aFNwYjJOZzgtbVdkUVJoN1VWT1RxVUhuTkJzIn0.eyJleHAiOjE3MTc3MDIyMDUsImlhdCI6MTcxNzcwMTkwNSwiYXV0aF90aW1lIjoxNzE3NzAxOTA0LCJqdGkiOiI2YzkzMjRjMi0wNDVlLTQ5YTktOTYzMi1kMjZlMjYyNWJjMzQiLCJpc3MiOiJodHRwOi8va2V5Y2xvYWstYXBwL3JlYWxtcy9HaWdhYml0SHViIiwiYXVkIjoib25lY3gtc2hlbGwtdWktY2xpZW50Iiwic3ViIjoiODc4ZDA5MjUtMzQ0OS00YzFjLWE2NzgtZmNkMmMyOGU3OGNjIiwidHlwIjoiSUQiLCJhenAiOiJvbmVjeC1zaGVsbC11aS1jbGllbnQiLCJub25jZSI6ImQ1OTcwMjBiLTQyYjItNDM3My04OTlkLTg2NDQ0MjY0YjYyMSIsInNlc3Npb25fc3RhdGUiOiI2ZjIxMWE1My00NzQ2LTRlNTAtYmM1ZC05ZWYyMzI0NDFmN2QiLCJhdF9oYXNoIjoiX0l6Y1RlNmJKbk9nWmxDTXVKRklEZyIsImFjciI6IjEiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicHJlZmVycmVkX3VzZXJuYW1lIjoib25lY3gtZ2ZudyIsInBhcnR5SWQiOlsiMTAwMTYiXSwib3JnSWQiOiJnZm53In0.Wvl1unz9oDltYWUzxha_L5ZrDGX8QViS2f317-5k9VFRCj0lfj7Qib4rEuAH_Oc5CY0jpobOmwW-QB5jlPSjlG6Xpoqjn2kacwLB056MeqtG71NOZJXKgZmaQdLO7RyCYwraGmsleNdPoVrSy50cbRJmkvknGGdlyJRuj4Fh_ksb8YscF8BSR8jDC--XBD-wqTE9ZNTqTYXDpOQM6NkR4kQalfBrOyBHRwBnxAsH6oyZhXpwLJehhGqXPyuzjAiU3oCEGbF5J0IjFoS-qXRKh1GOjFfTPFjhh4Y2HkgsXZ8e7yCdgvXlVy793fuwlo6_p_lqWTNM3nEvGjZxcBiucQ


for entry in "."/*.json
do
  #echo "$entry"
  file=$(basename "$entry")
  file=`echo $file | cut -d '.' -f 1`
  tenant=`echo $file | cut -d'_' -f1`
  product=`echo $file | cut -d'_' -f2`
  token_var_name=${tenant}_token
  token=${!token_var_name}
  #echo "curl -X POST -H "apm-principal-token: $token" -H 'Content-Type: application/json' "http://onecx-permission-svc//exim/v1/assignments/operator" -d @$entry"
  status_code=`curl --write-out %{http_code} --silent --output /dev/null -X POST -H "apm-principal-token: $token" -H 'Content-Type: application/json' "http://onecx-permission-svc/exim/v1/assignments/operator" -d @$entry`
  echo "Assignments uploaded for product $product were uploaded with status code $status_code"
done