=  FAQ & Help - Common Issues
:idprefix:
:idseparator: -
:imagesdir: ../images

This page lists common issues and respective solutions when using OneCX Local Environment.

== Keycloak reported as unhealthy
If the `keycloak-app` service is reported as unhealthy, please try to re-run the docker compose command to start the service again. In some cases, Keycloak might take a bit longer to start up, and re-running the command can help resolve the issue. This issue is more common in xref:documentation:local-env:general/versions/v1/v1.adoc[OneCX Local Environment v1] due to differences in the performed health checks.

== Docker Compose doesn't wait for all health checks to pass
In some cases, specifically when services don't have explicit dependencies defined via the `depends_on` directive, Docker Compose might not wait for all health checks to pass before finalizing the startup process. If you want to force Docker Compose to wait for all health checks to pass, you can use the `--wait` flag when starting the services. Example:
[source,bash]
----
  docker compose up -d --wait
----

== Services are not reachable or import of initial data fails
Some `onecx-local-env` services might take longer than others to start up and become fully operational. This can cause issues if you or a script you are running tries to access a service before it is ready. To prevent any issues it is recommended to wait for at least 30 seconds *after* all services are reported as healthy before accessing any service or running any import scripts. The link:https://github.com/onecx/onecx-local-env/blob/main/versions/v2/import-onecx.v2.sh[import script for OneCX Local Environment v2] has a built-in wait time of 30 seconds after all services are healthy to account for this. If you are using xref:documentation:local-env:general/versions/v1/v1.adoc[OneCX Local Environment v1], please ensure to manually wait for at least 30 seconds after all services are healthy before running the import script. 

If the link:https://github.com/onecx/onecx-local-env/blob/main/versions/v2/import-onecx.v2.sh[import script for OneCX Local Environment v2] or other access to services still fails, please try to increase the wait time to 60 seconds and restart the affected services if all else fails.