= Start the Environment
:idprefix:
:idseparator: -
:imagesdir: ../../../images

The *start-onecx.sh* script is used to start the OneCX Local Environment. By default, it will start a minimal set of services and import initial mock data on startup. Data imports will not overwrite any custom data that may already exist in the environment and can be skipped using the appropriate flag. The script can be run from the root directory of the *onecx-local-env* repository:

[source,bash]
----
./start-onecx.sh
----

== Available Flags
The script accepts several optional flags to customize its behavior. Some flags can be combined. The flags are:

-e::
The edition of OneCX to start. Supported editions are:
  * `v2`: Starts the current version of OneCX Local Environment (Default).
  * `v1`: Starts the legacy version of OneCX Local Environment (Not recommended for new setups).

-h:: Displays help information about the script and its available flags.

-p <profile-name>::
The profile to use when starting the environment. The supported profiles are:
  * `base`: Starts a minimal version of OneCX Local Environment with only essential services. (Default)
  * `all`: Starts all available services defined in the Docker Compose file.

-s::
Enables secure mode, which enforces authentication/authorization. (Default: disabled)

-x::
Skips the import of initial data after starting the services. (Default: import data according to the used profile)


[NOTE]
====
The script can be executed at any time. Docker checks the configuration of the services and restarts them if there are changes. Without changes, running services are not affected, and only missing services are started.
====

== Examples

Start essential Services::
The Docker services *essential* for OneCX are started. The necessary Docker volumes are created and required data are imported. Technically, the relevant services are marked with the *base* profile in the docker-compose file used.
[source,bash]
----
./start-onecx.sh
----

Start ALL Services::
*All* Docker services for OneCX are started. The necessary Docker volumes are created and required data are imported. Technically, the relevant services are marked with the *all* profile in the docker-compose file used.
[source,bash]
----
./start-onecx.sh -p all 
----

Start essential Services with Security enabled::
The Docker services *essential* for OneCX are started with enabled security authetication. The necessary Docker volumes are created but no data are imported.
[source,bash]
----
./start-onecx.sh -s -x
----


include::utilities.adoc[]
