= Integrate Microfrontends into OneCX
:idprefix:
:idseparator: -
:imagesdir: ../../../images

The script *toggle-mfes.sh* integrates (activates) a locally running microfrontend into the OneCX environment, allowing it to interact with other microfrontends. This process is also reversible. 

The script creates a small configuration file in Traefik, tailored to the local microfrontend. Traefik then forwards requests from the Docker network to the external local microfrontend.
It can be run from the root directory of the *onecx-local-env* repository.

The Traefik configuration files are stored in `init-data/traefik/active/`. Traefik immediately detects any changes there.

Here is the command to list the currently integrated microfrontends.:

[source,bash]
----
./toggle-mfes.sh  -l
----

== Precondition
Before a microfrontend can be successfully integrated into OneCX, it must be started.

.Start Angular *ng* Microfrontend on port 6021
[source,bash]
----
npm run start -- --port 6021 --host 0.0.0.0 --disable-host-check --public-host=http://localhost:6021
----

.Start Angular *nx* Microfrontend on port 6021
[source,bash]
----
npm run start -- --port=6021 --host 0.0.0.0 --disableHostCheck --publicHost=http://localhost:6021
----

.CheckPoint
Please check the microfrontend is up and running by using the *public host URL* (see start command) in Browser. The *remoteEntry.js* should be loaded.



== Available Flags
The script accepts several optional flags to customize its behavior. Some flags can be combined. The flags are:

-a::
Enable one or more local microfrontends. In addition to the microfrontend name, you can optionally specify a port and path. The default port is 4200.
If the mfe is one of OneCX Core products and no port is specified then predefined ports are used.

-c:: Cleanup, remove all existing configurations

-d:: Deactivate one or more local Microfrontends

-h:: Display this help and exit

-l::  List of currently integrated local microfrontends


== Examples

Integrate my App with specific path::
The local microfrontend `my-app` runs on `http://localhost:4200` (standard Angular).
`/my-app-path` is the path under which the microfrontend is accessible within OneCX.

[source,bash]
----
./toggle-mfes.sh  -a my-app::/my-app-path
----

Integrate several Apps::
Integrate the apps 'workspace' (with standard port) and user-profile on port `12345`.
Since no path is specified, the default path is used: /mfe/<name-of-microfrontend>

[source,bash]
----
./toggle-mfes.sh  -a workspace user-profile:12345
----


Deintegrate my App::
The -d option allows you to undo an integration. The same rule applies to the port: if the port is not 4200, it must be specified.

[source,bash]
----
./toggle-mfes.sh  -d my-app:12345
----


Deintegrate ALL Apps::
The Traefik configurations are being cleaned up: All specific configuration files for the Microfrontend integration are being deleted.

[source,bash]
----
./toggle-mfes.sh  -c
----
