= Update local Docker images
:idprefix:
:idseparator: -
:imagesdir: ../../../images

The *update-images.sh* script is used to renew local Docker images. It can be run from the root directory of the *onecx-local-env* repository.

Here is the command to display the available flags:

[source,bash]
----
./update-images.sh
----

[TIP]
====
To get an overview of the Docker images and their versions on your local machine, run the Docker command `*docker image ls*`. If images with the tag *<none>* are displayed, you can run the script with the parameter `*-c*` to clean them up.
====


== Available Flags
The script accepts several optional flags to customize its behavior. The available flags are:

-c::
Cleaned up orphaned images

-h::
Displays help information about the script and its available flags. If used then all other options are ignored.

-n <text>::
Name filter, update images which have <text> into image name


== Examples

Update all Images with `ui` in name::
The Docker which have *ui* in image name are pulled from remote registry.

[source,bash]
----
./update-images.sh  -n ui
----

Cleanup only::
Starting the script without any name filter will require a confirmation to proceed. Without this confirmation, the script will terminate.

With confirmation, all images will be checked and removed if they are outdated. If orphaned images are found (e.g., with *<none>* in their name), the script will attempt to delete them. This is only possible if the image is not in use.

[source,bash]
----
./update-images.sh  -c
----
