= OneCX Local Environment
:idprefix:
:idseparator: -
:imagesdir: ../images

`onecx-local-env` is the local development environment for OneCX products. It is based on Docker and Docker Compose, and enables developers to quickly run local instances of the OneCX Shell, selected OneCX products and their dependencies for development and testing purposes.

`onecx-local-env` can either be used as a standalone tool, or integrated into custom development environments via Git submodules. To avoid introducing breaking changes for any existing workflows or custom environments, multiple versions of `onecx-local-env` exist in parallel.

For more in-depth information on `onecx-local-env` including prerequisites, setup instructions, available versions and more please refer to the following documentation:

- xref:local-env:getting-started.adoc[Getting Started - Run OneCX locally]
- xref:troubleshooting:common-issues.adoc[Troubleshooting - Common Issues]

[NOTE]
.Quick Start
====
If you already followed all setup instructions mentioned in xref:local-env:getting-started.adoc[Getting Started - Run OneCX locally], you can complete the following steps to run and access a local OneCX environment:

. *Start the local environment:* To start a minimal local OneCX environment, run the following command from the `onecx-local-env` root directory: 
+
[source,bash]
----
  ./start-onecx.sh
----

. *Access your local OneCX environment:* After starting the local environment...
  * Open your web browser and navigate to `http://local-proxy/onecx-shell/admin`
  * Login using the following credentials:
    ** Username: `onecx`
    ** Password: `onecx`

. *Stop the local environment:* To stop the local OneCX environment, run the following command from the `onecx-local-env` root directory:
+
[source,bash]
----
./stop-onecx.sh
----

**Optional Steps**

. *Import mock data:* If you notice any errors or missing data in your local environment, re-importing the mock data may help resolve these issues. To import the mock data, run the following command from the `onecx-local-env` root directory:
+
[source,bash]
----
./import-onecx.sh
----
====