ifdef::env-site[]
include::partial$_attributes.adoc[]
endif::[]
:imagesdir: ../../images

:achitecture_microfrontends_link: xref:documentation:onecx-docs-overview:architecture/microservices.adoc[Microservices and Microfrontends]

:module_federation_webpack_link: xref:documentation:onecx-docs-overview:module-federation/webpack.adoc[Module Federation with Webpack]


= Use Webpack Module App in OneCX shell

When you have created a custom application and want to run it in the OneCX local environment, you need to add the application to the OneCX shell. This involves adding the application to the product store, adding the application to the workspace, and assigning permissions and roles for accessing the application.

This guide is created for webpack module apps. To see all supported types of microservices, see the {achitecture_microfrontends_link} documentation.

== Prerequisites

Before you can add your custom application to the OneCX, you need to have the following prerequisites in place:

* Your app needs to have webpack module federation implemented. See the {module_federation_webpack_link} documentation for details on how to implement webpack module federation in your application. 

* You have to add xref:./local-mfe.adoc[custom micro frontends] to the OneCX local environment with `./toggle-mfe` script.

== Guide Steps

. xref:./add_application_ui_component_product_store.adoc[Add the application and UI component to the product store]

. xref:./add_application_to_workspace.adoc[Add the application to the workspace]

. xref:./add_application_permissions.adoc[Assign permissions and roles (Optional)]