ifdef::env-site[]
include::partial$_attributes.adoc[]
endif::[]
:imagesdir: ../images

= AI Chat in OneCX Local Environment

The OneCX Local Environment supports AI Chat functionalities, allowing users to interact with AI-powered features for enhanced user experiences. +
This document provides an overview of how to enable and use AI Chat.

== Prerequisites
Before using AI Chat, ensure you have the following prerequisites in place:

* A working OneCX Local Environment set up. +
  If you haven't done this yet, follow the instructions in the xref:./setup.adoc[Setting up] documentation.
* A started OneCX Local Environment with the *all* profile enabled. +
  Refer to the xref:./scripts/start.adoc#start-all-services[Start OneCX with all profile] documentation for instructions on starting the environment with the appropriate profile.
* An active AI service subscription and a valid *App Key*. This key is required to access AI functionalities within OneCX. +
  You can obtain an App Key from your AI service provider.


== Set up AI Functionalities
To prepare the AI Functionalities, follow these steps:

. Start OneCX with the *all* profile. +
  During the startup process, the necessary AI services will be started.
+
[source,bash]
----
./start-onecx.sh -p all
----

. Import AI data using the following script. You will be prompted to enter your *App Key*:
+
[source,bash]
----
./import-onecx.sh -x -d ai
----

. Verify that the AI services are running correctly by checking the logs of the relevant Docker containers.

[TIP]
====
Due to the API Key being sensitive information, it is not stored in the OneCX Local Environment by default. +
You can provide the API Key in a file named *api_key* within the root directory of the `onecx-local-env`. It is automatically read in during the AI ​​data import process (step 2 above)..
====


== Using AI Chat
Once AI Functionalities are prepared, you can start using AI Chat within your OneCX applications. +
Here are some common use cases:
