= Advanced - Scripts - `stop-onecx.sh`
:idprefix:
:idseparator: -
:imagesdir: ../images

The `stop-onecx.sh` script is used to stop the OneCX Local Environment. To stop the environment, the script can be run from the root directory of the `onecx-local-env` repository:

[source,bash]
----
./stop-onecx.sh
----

== Available Flags
The `stop-onecx.sh` script accepts several optional flags to customize its behavior. The available flags are:

* `-c`: Cleans up all volumes associated with the OneCX Local Environment when stopping the services. This will remove all data stored in the volumes, so use this flag with caution. (Default: disabled)
* `-e`: The edition of OneCX to stop. This must match the edition that was used to start the environment. Supported editions are:
** `v2` (Default).
** `v1`
* `-h`: Displays help information about the script and its available flags.
* `-p <profile-name>`: The profile to use when stopping the environment. This must match the profile that was used to start the environment. The supported profiles are:
** `base` (Default)
** `all`